obj-y	+= clock.o
obj-y	+= components.o
obj-y	+= device.o
obj-y	+= idle.o
obj-y	+= ipc.o
obj-y	+= irq.o
obj-y	+= kservice.o
obj-y	+= mem.o
obj-y	+= memheap.o
obj-y	+= mempool.o
obj-y	+= object.o
obj-y	+= scheduler.o
obj-y	+= signal.o
obj-y	+= slab.o
obj-y	+= thread.o
obj-y	+= timer.o

subdir-ccflags-$(CONFIG_CC_OPTIMIZE_LIBS_FOR_SPEED) += -O2