obj-y	+= cp15_gcc.o
obj-y	+= context_gcc.o
obj-y	+= vector_gcc.o
obj-y	+= exception.o
obj-y	+= mmu.o
obj-y	+= pmu.o
obj-y	+= stack.o
obj-y	+= cpu.o
obj-y	+= interrupt.o
obj-y	+= gic.o
obj-y	+= timer.o
obj-y	+= stack_setup.o
obj-y	+= relocation.o
obj-y	+= timer_vexpress.o

subdir-ccflags-$(CONFIG_CC_OPTIMIZE_LIBS_FOR_SPEED) += -O2